#!/bin/bash
### BEGIN INIT INFO
# Provides: hal-tweeter
# Required-Start: $local_fs $network mosquitto
# Required-Stop: $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: haldor tweeter
# Description: automated makerspace openness tweeter
### END INIT INFO
# Haldor init script

#/home/tweeter/haldor-tweeter/start.sh "$@"
sudo -H -u tweeter bash -c "/home/tweeter/haldor-tweeter/start.sh \"$@\""
